[package]
name = "multi-party-ed25519"
version = "0.1.0"
authors = [
    "Omer <omer@kzencorp.com>",
    "Gary <gary@kzencorp.com>"
]

[lib]
crate-type = ["dylib"]

[dependencies]
curv = { git = "https://github.com/KZen-networks/curv" , features =  ["ed25519"]}
hex = "0.3.2"
